### ISSUE TITLE
Rebuild the docker image

### ISSUE THREAD

**Issue by anas-aso** [xueshanf/docker-git-crypt#2]
Since Alpine had switched to libressl, there is now an issue with this docker image.
```
apk update && apk add gnupg
[...]
ERROR: libcrypto1.1-1.1.1b-r1: trying to overwrite etc/ssl/openssl.cnf owned by libressl2.5-libcrypto-2.5.5-r3.
```
This issue is already solved in the latest build of `alpine:edge`
Can you please rebuild the docker image to get it fixed ?

**Comment by xueshanf** [comment]
@anas-aso I have rebuilt the image and also updated git-crypt to 0.6.0. Let me know if there are any issues.

**Comment by anas-aso** [comment]
I confirm the issue is solved. Thanks @xueshanf for fixing it.
